#!/bin/bash

# get the clone url so we can start fresh
CLONE_URL=$(git config --get remote.origin.url)

if [[ $? -ne 0 ]]; then
    echo 'Could not get upstream git url!' >&2
    exit 1
fi

# create a temporary directory to do our work
STARTDIR=$(pwd)
WORKDIR=$(mktemp -d)
cd "$WORKDIR"

git clone --recursive "$CLONE_URL" build

# remove the .git directory which bloats the build
rm -rf build/.git

# build our thing
cd build
make
cd ..

# package it all up
mv build "$1"
tar cvf "$1".tar "$1"
gzip --best "$1".tar

# keep the archive since we're going to cleanup
mv "$1".tar.gz "$STARTDIR"/

# clean up our temporary directory and contents
cd "$STARTDIR"
rm -rf "$WORKDIR"
