#!/bin/bash

#   Copyright 2017 Mario Finelli
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# get the clone url so we can start fresh
CLONE_URL=$(git config --get remote.origin.url)

if [[ $? -ne 0 ]]; then
    echo 'Could not get upstream git url!' >&2
    exit 1
fi

# create a temporary directory to do our work
STARTDIR=$(pwd)
WORKDIR=$(mktemp -d)
cd "$WORKDIR"

git clone --recursive "$CLONE_URL" build

# remove the .git directory which bloats the build
rm -rf build/.git

# build our thing
cd build
make

if [ $? -ne 0 ]; then
    echo 'Build failed!' >&2
    exit 1
fi

cd ..

# package it all up
mv build "$1"
tar cvf "$1".tar "$1"
gzip --best "$1".tar

# keep the archive since we're going to cleanup
mv "$1".tar.gz "$STARTDIR"/

# clean up our temporary directory and contents
cd "$STARTDIR"
rm -rf "$WORKDIR"
